name: bada_kids_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.6
  sms_autofill: ^2.3.1
  http: ^1.2.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  kakao_map_plugin: ^0.2.5
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1
  firebase_in_app_messaging: ^0.7.4+18
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  kakao_flutter_sdk: ^1.9.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
    - assets/gif/
    - assets/lottie/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 900
    - family: Spoqa
      fonts:
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 900